#!/bin/sh
set -x #echo on



#==========
#==  First copy entire dir.  Keep for incremental comparison.
#==  Second create compressed archive.
#==========

PRODUCTION_DIR="/root/Spigot"

BACKUP_DIR="/root/Spigot/Backups"
DAILY_PREFIX=${BACKUP_DIR}/Spigot_daily_$(date '+%a')
DAILY_DIR=${DAILY_PREFIX}_dir"
DAILY_DEST_DIR=${DAILY_PREFIX}_dir/Spigot"
DAILY_DEST_ARCHIVE=${DAILY_PREFIX}.tar.gz

rm -rf $DAILY_DIR
mkdir  $DAILY_DIR

cp --archive   $PRODUCTION_DIR   $DAILY_DEST_DIR

tar zcfp   $DAILY_DEST_ARCHIVE   $DAILY_DEST_DIR 






#==========
#==  Remove directories older than needed for incremental snapshots
#==   * 1 day is needed for incremental snapshots
#==   * Remaining archives take up less space and cycle every 7 days
#==========
DAYS_OLD=2
find ~/Backups/Spigot_daily_*_dir      -maxdepth 0   -mtime +${DAYS_OLD}  
echo "--- Deleting old directories ---"
find ~/Backups/Spigot_daily_*_dir      -maxdepth 0   -mtime +${DAYS_OLD} -exec rm -rf {} \; 
