#!/bin/sh
set -x #echo on
echo "Running hourly backup at $(date +%Y-%m-%d_%H:%M:%S)"
cd /root/Backups

#=== Save just the changes ===
PRODUCTION_DIR=/root/Spigot
SAVE_HOURLY_DIFF_BASE=/root/Backups/Spigot_hourly_$(date '+%a-%H')_dir
SAVE_HOURLY_DIFF_DIR=${SAVE_HOURLY_DIFF_BASE}/Spigot  # Latest changes go here
LAST_SAVED_DAILY_DIR=$(ls -dt /root/Backups/Spigot_daily_*_dir/Spigot  | head -n1)

rm -rf $SAVE_HOURLY_DIFF_BASE  # Remove old dir; New one will be created w/ rsync
mkdir $SAVE_HOURLY_DIFF_BASE

#=== Trailing slashes (/) are crucial for incremental to work
RSYNC_COMMAND="rsync  --stats --archive --compare-dest=$LAST_SAVED_DAILY_DIR/ $PRODUCTION_DIR/ $SAVE_HOURLY_DIFF_DIR/"  # To test add --dry_run
echo $RSYNC_COMMAND  # Just to test
$RSYNC_COMMAND


# Delete empty directories; rsync "compare-dest" creates empty ones even if no files changed
find $SAVE_HOURLY_DIFF_DIR -depth -type d -empty -delete


#==========
#== Remove both directories and files older than certain # of days
#==========
DAYS_OLD=2
echo "--- The following will be deleted ---"
find ~/Backups/Spigot_hourly_*_dir  -maxdepth 0   -mtime +${DAYS_OLD}  
find ~/Backups/Spigot_hourly_*tar*                -mtime +${DAYS_OLD}  
echo "--- Deleting ---"
find ~/Backups/Spigot_hourly_*_dir  -maxdepth 0   -mtime +${DAYS_OLD}  -exec rm -rf {} \;
find ~/Backups/Spigot_hourly_*tar*                -mtime +${DAYS_OLD}  -delete


#=============================
# MATCH_COUNT=$(rsync  --stats --archive --dry-run --compare-dest=/root/rsynch_test/saved/ /root/rsynch_test/latest/ /root/rsynch_test/changes/ |  grep "Number of created files: 0\|Number of regular files transferred: 0" | wc -l)
# 
# if ["$MATCH_COUNT" = "2"] then  # No changes
#=============================
