#!/bin/sh
set -x #echo on
echo "Running hourly backup at $(date +%Y-%m-%d_%H:%M:%S)"
cd /root/Backups

#=== Save just the changes ===
PRODUCTION_DIR=/root/Spigot/
SAVE_HOURLY_DIFF_DIR=/root/Backups/Spigot_hourly_$(date '+%a-%H')/  # Latest changes go here
LAST_SAVED_DAILY_DIR=$(ls -dt /root/Backups/Spigot_daily_*/  | head -n1)

echo "rm -rf $SAVE_HOURLY_DIFF_DIR" 
rm -rf $SAVE_HOURLY_DIFF_DIR  # Remove old dir; New one will be created w/ rsync


RSYNC_COMMAND="rsync  --stats --archive --compare-dest=$LAST_SAVED_DAILY_DIR $PRODUCTION_DIR $SAVE_HOURLY_DIFF_DIR"  # To test add --dry_run
echo $RSYNC_COMMAND  # Just to test
$RSYNC_COMMAND


# Delete empty directories; rsync "compare-dest" creates empty ones even if no files changed
find $SAVE_HOURLY_DIFF_DIR -depth -type d -empty -delete





#==========
#==  Remove both directories and files older than certain # of days
#==========
DAYS_OLD=2
echo "--- The following will be deleted ---"
find ~/Backups/Spigot_hourly_*      -maxdepth 0   -mtime +${DAYS_OLD}  
find ~/Backups/Spigot_hourly_*tar*                -mtime +${DAYS_OLD}  
echo "--- Deleting ---"
find ~/Backups/Spigot_hourly_*      -maxdepth 0   -mtime +${DAYS_OLD}  -exec rm -rf {} \;
find ~/Backups/Spigot_hourly_*tar*                -mtime +${DAYS_OLD}  -delete

