#!/bin/sh
set -x #echo on

#==========
#==  Make archive of entire source directory
#==========

PARAMS=zcfp  #  --atime-preserve does not work with this version
DEST_FILE=~/Backups/Spigot_daily_$(date '+%a').tar.gz
DEST_PREFIX=~/Backups/Spigot_daily_
SOURCE_DIR=~/
SOURCE_FILE=Spigot/
LOG_FILE=~/Backups/backup_daily.log

tar $PARAMS   $DEST_FILE  -C $SOURCE_DIR  $SOURCE_FILE 
